server:
  port: 8090
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #url 패턴 매칭 전략
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
  config:
    import: classpath:local-profile.yml
logging:
  level:
    root: WARN
    rocket.planet: DEBUG

---
spring.config.activate.on-profile: local-profile
---


