server:
  port: 8090
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #url 패턴 매칭 전략
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    #    hibernate:
    #      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 1000
  config:
    import: classpath:local-profile.yml
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    rocket.planet: DEBUG
decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring.config.activate.on-profile: local-profile
---


